# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `migration_signature` gem.
# Please instead update this file by running `bin/tapioca gem migration_signature`.

module MigrationSignature
  class << self
    def build_all; end
    def build_file(file); end
    def check_all; end
    def config; end
  end
end

class MigrationSignature::Config
  # @return [Config] a new instance of Config
  def initialize(opts = T.unsafe(nil)); end

  def all_runnable_files; end

  # @return [Boolean]
  def ignore?(file); end

  def migration_dir; end

  private

  def regexp_ignores; end
  def string_ignores; end

  class << self
    def load; end
  end
end

MigrationSignature::Config::CONFIG_FILE_PATH = T.let(T.unsafe(nil), String)
MigrationSignature::Config::DEFAULTS = T.let(T.unsafe(nil), Hash)
class MigrationSignature::InvalidSignatureError < ::StandardError; end

class MigrationSignature::MigrationFile
  # @return [MigrationFile] a new instance of MigrationFile
  def initialize(path_or_version); end

  def basename; end

  # @return [Boolean]
  def ignore?; end

  def update_signature!; end

  # @raise [MigrationSignature::InvalidSignatureError]
  def validate_signature!; end

  private

  def lines; end
  def new_source_signature_line; end

  # Returns the value of attribute path.
  def path; end

  # @return [Boolean]
  def signature?; end

  def signature_line_number; end
  def source_signature; end

  # @return [Boolean]
  def valid_signature?; end

  def write_to_file(new_lines); end

  class << self
    def resolve_full_name(path_or_version); end
  end
end

MigrationSignature::MigrationFile::MIGRATION_SIG_PREFIX = T.let(T.unsafe(nil), String)

module MigrationSignature::MigratorEnhancement
  def migrate; end
  def run; end
end

class MigrationSignature::Railtie < ::Rails::Railtie; end
