require: rubocop-rails

Style/Documentation:
  Enabled: false

AllCops:
  NewCops: enable 
  Exclude:
    - "db/**/*"
    - "config/**/*"
    - "script/**/*"
    - "bin/{rails,rake}"
    - "vendor/**/*"
    - "spec/fixtures/**/*"
    - "tmp/**/*"
    - "bin/**"
    - "app/controllers/turbo_devise_controller.rb"
    - "/node_modules/**"

Rails:
  Enabled: true

Layout/LineLength:
  Max: 120
Metrics/MethodLength:
  Max: 20
