default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: west_chestnut_portal_dev


test:
  <<: *default
  database: west_chestnut_portal_test

staging:
  <<: *default
  database: west_chestnut_portal_staging

production:
  <<: *default
  database: west_chestnut_portal_prod
